// 101 Psychological Defenses - Bilingual Data
// Based on '101 Defenses: How the Mind Shields Itself' by Jerome S. Blackman

const phaseInfo = {
  oral: { en: 'Oral Phase (0-3 years)', zh: '口欲期 (0-3岁)' },
  anal: { en: 'Anal Phase (1.5-5 years)', zh: '肛欲期 (1.5-5岁)' },
  phallic: { en: 'First Genital Phase (2-6 years)', zh: '第一性器期 (2-6岁)' },
  latency: { en: 'Latency Phase (6-11 years)', zh: '潜伏期 (6-11岁)' },
  adolescent: { en: 'Adolescence & Later (13-20+ years)', zh: '青春期及以后 (13-20岁+)' },
  assorted: { en: 'Assorted', zh: '杂类' },
};

const defenses = [
  {
    "id": 1,
    "phase": "oral",
    "phaseEn": "Oral Phase (0-3 years)",
    "phaseZh": "口欲期 (0-3岁)",
    "en": "Projection",
    "zh": "投射",
    "defEn": "You attribute your own stuff to another person.",
    "defZh": "你把自己的想法、感受或冲动归结到别人身上。",
    "fullDefEn": "You attribute your own stuff to another person.",
    "caseEn": "Ms. D reported that she thought her boss was angry at her the day before.",
    "caseZh": "D女士因为上司让她赶一份备忘录而感到愤怒，但她没有意识到自己的愤怒，反而整夜担心上司在生她的气。经过讨论后她意识到，是她自己把愤怒投射到了上司身上。"
  },
  {
    "id": 2,
    "phase": "oral",
    "phaseEn": "Oral Phase (0-3 years)",
    "phaseZh": "口欲期 (0-3岁)",
    "en": "Introjection",
    "zh": "内摄",
    "defEn": "You form an image of another person.",
    "defZh": "你在心里构建出另一个人的形象。",
    "fullDefEn": "You form an image of another person.",
    "caseEn": "Mr. Z would already be dead. A couple of Monday mornings later, on arriving in my office after the",
    "caseZh": "Z先生每次被父亲贬低后就想自杀。治疗师解释这是他把自己对父亲的愤怒转向了自身。后来他告诉治疗师，在又一次被父亲贬低后，他本想自杀，但脑海中浮现治疗师的声音说'因为生父亲的气而伤害自己是愚蠢的'，于是他活了下来——这就是内摄在起作用。"
  },
  {
    "id": 3,
    "phase": "oral",
    "phaseEn": "Oral Phase (0-3 years)",
    "phaseZh": "口欲期 (0-3岁)",
    "en": "Hallucination",
    "zh": "幻觉",
    "defEn": "You see or hear what you are trying not to think about—wishes, comments, fantasies, or criticisms—with no reality testing. Anal Phase (1.5 to 5 years)",
    "defZh": "你看到或听到自己试图不去想的东西——愿望、意见、幻想或批评——且没有现实检验。",
    "fullDefEn": "You see or hear what you are trying not to think about—wishes, comments, fantasies, or criticisms—with no reality testing. Anal Phase (1.5 to 5 years)",
    "caseEn": "",
    "caseZh": "精神病患者看到或听到自己试图不去想的念头——愿望、批评或幻想——但无法区分这些是自己的思想还是外部现实，因为现实检验功能已经失效。"
  },
  {
    "id": 4,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Projective Identification",
    "zh": "投射性认同",
    "defEn": "Three common ways this term is used: a. Projecting so much of yourself onto someone else that you massively distort him or her. b. Stimulating in someone else your unpleasant affects (“misery loves co...",
    "defZh": "三种常见用法：a) 把自己大量投射到他人身上以至于严重扭曲对方；b) 在他人身上激起自己的不愉快情感；c) 在他人身上激起自己的不愉快情感，同时表现得像那个曾经让你痛苦的人。",
    "fullDefEn": "Three common ways this term is used: a. Projecting so much of yourself onto someone else that you massively distort him or her. b. Stimulating in someone else your unpleasant affects (“misery loves company”). c. Stimulating in someone else your unpleasant affects, plus acting like the person who had made you feel so bad.",
    "caseEn": "Ms. UU, a 23-year-old depressed single woman, described problems in her",
    "caseZh": "23岁的UU女士因为治疗师迟到一分钟而大发雷霆，指责治疗师'把她当成低等生物'。治疗师感到被无理指责却无从辩解——这正是UU女士面对父亲时的感受。通过投射性认同，她让治疗师体验到了她的无助愤怒。"
  },
  {
    "id": 5,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Projective Blaming",
    "zh": "投射性指责",
    "defEn": "You unfairly blame somebody else for your problem.",
    "defZh": "你为自己的问题而不公正地指责他人。",
    "fullDefEn": "You unfairly blame somebody else for your problem.",
    "caseEn": "At 9:30 p.m., a father comes out of his study where he was using the",
    "caseZh": "晚上9点半，父亲从书房出来发现儿子还没做作业，立刻指责母亲：'为什么Jimmy还没做作业？'母亲刚挂了工作电话，立刻反驳：'我一直很忙！你为什么不管他做作业？！'这是一个家庭中常见的投射性指责。"
  },
  {
    "id": 6,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Denial",
    "zh": "否认",
    "defEn": "Assumes you’ve perceived reality (reality sense is functional): a. Denial per se: Disavowal of a reality in spite of overwhelming evidence of its existence. b. Denial in deed: Behavior that symbolical...",
    "defZh": "假定你已经感知到了现实，但却加以否认。包括：本质否认、行为上的否认、幻想中的否认、言语上的否认。",
    "fullDefEn": "Assumes you’ve perceived reality (reality sense is functional): a. Denial per se: Disavowal of a reality in spite of overwhelming evidence of its existence. b. Denial in deed: Behavior that symbolically says, “That nasty reality isn’t true!” c. Denial in fantasy: Maintaining erroneous beliefs so you won’t have to see the reality. d. Denial by words: Using special words to convince yourself of the falsity of a reality.",
    "caseEn": "Mr. Y, a 48-year-old man, was admitted to a mental hospital just after he",
    "caseZh": "一个酗酒者即使被逮捕、丢工作、家庭破裂，仍然坚称'我能控制自己的饮酒'。通过言语上的否认，他避免面对自己已经失控的现实。"
  },
  {
    "id": 7,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Dedifferentiation (Self-Object Fusion)",
    "zh": "去分化（自体-客体融合）",
    "defEn": "You become whatever someone else wants you to be.",
    "defZh": "你变成别人想要你成为的样子。",
    "fullDefEn": "You become whatever someone else wants you to be.",
    "caseEn": "In West Side Story (Laurents, Bernstein, Sondheim, & Robbins, 1956), the",
    "caseZh": "一位女士嫁给丈夫后，完全按照丈夫的喜好生活——他说喜欢短发她就剪短发，他说不喜欢她的朋友她就断绝来往。她变成了丈夫想要的样子，失去了自我。"
  },
  {
    "id": 8,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Splitting",
    "zh": "分裂",
    "defEn": "You see certain people as purely hostile (McDevitt, 1985), and others as purely loving. Or, you now hate the devil you loved.",
    "defZh": "你把某些人看作纯粹敌对的，另一些人看作纯粹可爱的。或者你现在痛恨你曾经爱过的人。",
    "fullDefEn": "You see certain people as purely hostile (McDevitt, 1985), and others as purely loving. Or, you now hate the devil you loved.",
    "caseEn": "Splitting and projection contribute to the child’s poem:",
    "caseZh": "一位边缘人格患者在治疗初期把治疗师理想化为'完美的拯救者'，两个月后因为治疗师说了一句中性的话，立刻将治疗师视为'完全不称职的骗子'。这就是分裂——无法同时容纳好与坏的面向。"
  },
  {
    "id": 9,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Animism",
    "zh": "泛灵论",
    "defEn": "You give human qualities to nonhuman entities.",
    "defZh": "你把人的属性赋予非人类的实体。",
    "fullDefEn": "You give human qualities to nonhuman entities.",
    "caseEn": "Although this is a prominent mechanism in psychotic adults, it is also common",
    "caseZh": "一个孩子对着玩具熊说话，安慰它不要害怕打雷。通过泛灵论，孩子把自己的恐惧赋予了玩具熊，然后通过安慰玩具熊来安慰自己。"
  },
  {
    "id": 10,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Deanimation",
    "zh": "去生命化",
    "defEn": "The person you see isn’t human, so you don’t have to worry.",
    "defZh": "你眼中的人不是真正的人，这样你就不必担忧。",
    "fullDefEn": "The person you see isn’t human, so you don’t have to worry.",
    "caseEn": "A man in treatment with me reported that he disliked seeing me outside my",
    "caseZh": "急救医生在面对严重烧伤的病人时，在内心把病人看作'一具需要处理的躯体'而非一个活生生的人。这种去生命化保护医生免于被恐惧和无助感淹没。"
  },
  {
    "id": 11,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Reaction-Formation",
    "zh": "反向形成",
    "defEn": "You feel opposite (e.g., so nice you can’t tell you’re angry).",
    "defZh": "你感受到相反的情感（比如你太友善了，以至于看不出你在生气）。",
    "fullDefEn": "You feel opposite (e.g., so nice you can’t tell you’re angry).",
    "caseEn": "A man laughed as he described a childhood memory of his mother chasing",
    "caseZh": "一位母亲对不听话的孩子感到极度愤怒，但表现出来的是过度的温柔和关切。她无法意识到自己的愤怒，因为她用反向形成将其转化为相反的情感。"
  },
  {
    "id": 12,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Undoing and Rituals",
    "zh": "撤销与仪式",
    "defEn": "You go against your conscience (superego). Or you do what you feel guilty about and atone by punishing yourself in another symbolic act.",
    "defZh": "你违背自己的良心（超我），或者做了感到内疚的事后用象征性的行为惩罚自己来赎罪。",
    "fullDefEn": "You go against your conscience (superego). Or you do what you feel guilty about and atone by punishing yourself in another symbolic act.",
    "caseEn": "Undoing can also occur in obsessional rituals, where you fight",
    "caseZh": "一个人对伴侣有不忠的想法后，感到极度内疚，于是回家后主动做所有家务、给伴侣买礼物。这些撤销与仪式行为象征性地'赎罪'。"
  },
  {
    "id": 13,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Isolation (of Affect)",
    "zh": "情感隔离",
    "defEn": "You are unaware of the sensation of affects.",
    "defZh": "你意识不到情感的感觉部分。",
    "fullDefEn": "You are unaware of the sensation of affects.",
    "caseEn": "A woman tells you matter-of-factly that her husband has not made love to",
    "caseZh": "一位车祸幸存者能够用冷静甚至冷淡的语气详细描述事故的每一个细节，但完全没有感受到与之相关的恐惧或悲伤——情感被隔离了。"
  },
  {
    "id": 14,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Externalization",
    "zh": "外化",
    "defEn": "You think “Society” will criticize you, but actually you feel guilty.",
    "defZh": "你认为“社会”会批评你，但其实是你自己感到内疚。",
    "fullDefEn": "You think “Society” will criticize you, but actually you feel guilty.",
    "caseEn": "DEFENSES THAT ARISE IN PSYCHOSEXUAL DEVELOPMENT 29",
    "caseZh": "一个人在工作中犯了错，却不断说'公司肯定会开除我'。实际上没有任何人批评他，是他自己的内疚感被外化了，变成了'社会/公司会指责我'。"
  },
  {
    "id": 15,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Turning on the Self",
    "zh": "转向自身",
    "defEn": "You’re angry at someone, but attack/kill yourself instead.",
    "defZh": "你对某人生气，却转而攻击或伤害自己。",
    "fullDefEn": "You’re angry at someone, but attack/kill yourself instead.",
    "caseEn": "Once, in interviewing a suicidal woman from Mexico (in Spanish), I",
    "caseZh": "J女士的男友放了她鸽子，她感到愤怒但没有表达。当晚她用刀片划伤了自己的手臂。她把对男友的愤怒转向了自身。"
  },
  {
    "id": 16,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Negativism",
    "zh": "消极主义",
    "defEn": "You refuse to cooperate, and treat other people condescendingly.",
    "defZh": "你拒绝合作，并居高临下地对待他人。",
    "fullDefEn": "You refuse to cooperate, and treat other people condescendingly.",
    "caseEn": "A 42-year-old man consults you because his mother “forced” him to come",
    "caseZh": "一位青少年在学校被要求完成额外作业，他不仅拒绝，还对老师说'你这破课根本不值得我花时间'。他用消极主义和贬低来掩盖对失败的恐惧。"
  },
  {
    "id": 17,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Compartmentalization",
    "zh": "分隔化",
    "defEn": "You inhibit yourself from making connections.",
    "defZh": "你阻止自己在不同想法之间建立联系。",
    "fullDefEn": "You inhibit yourself from making connections.",
    "caseEn": "Ms. W, a 28-year-old woman with problems in heterosexual relationships,",
    "caseZh": "一位商人周一至周五在外面花天酒地，但周末回家时是个虔诚的教徒。他阻止自己在'享乐的自己'和'道德的自己'之间建立联系——分隔化让他不必面对内心的冲突。"
  },
  {
    "id": 18,
    "phase": "anal",
    "phaseEn": "Anal Phase (1.5-5 years)",
    "phaseZh": "肛欲期 (1.5-5岁)",
    "en": "Hostile aggression",
    "zh": "敌意攻击",
    "defEn": "You get into fights to hide unpleasant feelings. First Genital Phase (2 to 6 years)",
    "defZh": "你用打架斗殴来掩盖不愉快的感受。",
    "fullDefEn": "You get into fights to hide unpleasant feelings. First Genital Phase (2 to 6 years)",
    "caseEn": "A 29-year-old man sheepishly admitted, in session, that when his wife had",
    "caseZh": "一个在学校被欺负的男孩，回家后毫无理由地打了妹妹。他用敌意攻击来掩盖在学校的无力和羞辱感。"
  },
  {
    "id": 19,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Displacement",
    "zh": "置换",
    "defEn": "You feel one way toward a person, but shift it to another person or situation.",
    "defZh": "你对一个人有某种感受，却把它转移到了另一个人或情境上。",
    "fullDefEn": "You feel one way toward a person, but shift it to another person or situation.",
    "caseEn": "A woman’s 11-year-old son left his history book in school. She",
    "caseZh": "一个人在工作中被老板痛骂，回家后对妻子因为一件小事大吼大叫。他把对老板的愤怒置换到了妻子身上。"
  },
  {
    "id": 20,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Symbolization",
    "zh": "象征化",
    "defEn": "You give irrational meaning to some aspect of mental functioning.",
    "defZh": "你给心理功能的某些方面赋予不合理的含义。",
    "fullDefEn": "You give irrational meaning to some aspect of mental functioning.",
    "caseEn": "",
    "caseZh": "一位来访者在梦中反复出现'被困在笼子里的鸟'。在治疗中发现，这只鸟象征着她对婚姻的感受——被困住但无法表达。"
  },
  {
    "id": 21,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Condensation",
    "zh": "凝缩",
    "defEn": "You weld together disparate ideas that are contiguous.",
    "defZh": "你把完全不同的、但彼此邻近的想法焊接在一起。",
    "fullDefEn": "You weld together disparate ideas that are contiguous.",
    "caseEn": "Mr. V sees a Lexus in his therapist’s parking lot, and assumes it belongs to",
    "caseZh": "一个人在梦中同时见到了他母亲和他的小学老师，两人的形象融合成了一个角色。现实中他对两人有类似的被控制感，梦境通过凝缩将它们焊接在一起。"
  },
  {
    "id": 22,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Illusion Formation or Daydreaming",
    "zh": "幻想形成或白日梦",
    "defEn": "You consciously visualize a scene that is upsetting or pleasant, and know it’s a fantasy.",
    "defZh": "你有意识地想象一个令人不安或愉快的场景，并知道那只是幻想。",
    "fullDefEn": "You consciously visualize a scene that is upsetting or pleasant, and know it’s a fantasy.",
    "caseEn": "A woman reported a repetitive “vision” of a pleasant, “fresh” green field in",
    "caseZh": "一位女性报告说，每当工作压力大时，她会反复'看到'一片宁静的绿色田野。她知道这是幻想，但这个白日梦帮助她暂时逃避焦虑。"
  },
  {
    "id": 23,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Prevarication",
    "zh": "搪塞（故意撒谎）",
    "defEn": "You lie on purpose, for a reason.",
    "defZh": "你出于某种原因故意撒谎。",
    "fullDefEn": "You lie on purpose, for a reason.",
    "caseEn": "I once confronted a 10-year-old boy I was evaluating by telling him I knew",
    "caseZh": "一个青少年对父母说自己昨晚在图书馆学习，实际上他和朋友去了酒吧。他故意撒谎以避免被惩罚。"
  },
  {
    "id": 24,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Confabulation",
    "zh": "虚构（无意识撒谎）",
    "defEn": "You lie without knowing it, to relieve lowered self-esteem.",
    "defZh": "你在没有意识到的情况下撒谎，以缓解低自尊。",
    "fullDefEn": "You lie without knowing it, to relieve lowered self-esteem.",
    "caseEn": "An 86-year-old woman with Alzheimer’s Disease was brought by her",
    "caseZh": "一位女士告诉朋友自己毕业于名校，实际上她只是在那里上过一个暑期课程。她在无意识中撒谎来缓解对自己学历的自卑感。"
  },
  {
    "id": 25,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Repression",
    "zh": "压抑",
    "defEn": "You forget thoughts without wanting to.",
    "defZh": "你忘记了某些想法，而并非真的想要忘记。",
    "fullDefEn": "You forget thoughts without wanting to.",
    "caseEn": "",
    "caseZh": "一位女士完全忘记了与丈夫约定的'亲密约会'，因为前一天晚上丈夫为吸大麻的事与她争吵。她对丈夫的愤怒被压抑了——约会从记忆中消失。"
  },
  {
    "id": 26,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Negative Hallucination",
    "zh": "负性幻觉",
    "defEn": "You don’t see something upsetting that’s right in front of you.",
    "defZh": "你对就在眼前令人不安的事物视而不见。",
    "fullDefEn": "You don’t see something upsetting that’s right in front of you.",
    "caseEn": "A 39-year-old man who had been in treatment for several months asked,",
    "caseZh": "一位母亲没有'看到'女儿手臂上的自残伤痕，尽管伤痕就在眼前。她对女儿可能有心理问题的焦虑导致她产生了负性幻觉。"
  },
  {
    "id": 27,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Libidinal Regression [Psychosexual Regression]",
    "zh": "力比多退行（性心理退行）",
    "defEn": "You are afraid of sex and assertiveness, so you become dependant (oral) or stubborn (anal) instead.",
    "defZh": "你害怕性和独立自强，于是变得依赖（口欲）或顽固（肛欲）。",
    "fullDefEn": "You are afraid of sex and assertiveness, so you become dependant (oral) or stubborn (anal) instead.",
    "caseEn": "A 31-year-old married homemaker consulted me because she was critical",
    "caseZh": "一位35岁的男性在面临晋升后，开始过度依赖妻子做所有决定，甚至吃什么都要问妻子。面临独立和成功的压力，他退行到了口欲期的依赖状态。"
  },
  {
    "id": 28,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Ego Regression",
    "zh": "自我退行",
    "defEn": "Three ways this term is used: a. Interference with a function: Your ego function or ego strength stops working, so you can’t feel something unpleasant. b. Reversion to earlier defense mechanisms: You ...",
    "defZh": "三种用法：a) 自我功能或自我力量停止工作，使你感受不到不快；b) 倒退到早期防御机制；c) 防御失效，通过失败来惩罚自己以减轻内疚。",
    "fullDefEn": "Three ways this term is used: a. Interference with a function: Your ego function or ego strength stops working, so you can’t feel something unpleasant. b. Reversion to earlier defense mechanisms: You start using defense mechanisms that arose in an early stage of development. c. Inefficient defensive operations: Your defenses fail to shut off affect, and the failure relieves guilt by punishing you.",
    "caseEn": "Ms. U, a 45-year-old successful businesswoman, consulted me because of",
    "caseZh": "一位通常逻辑清晰的高管在讨论他的婚姻问题时，突然'脑子一片空白'，无法组织思维。他的自我功能暂时停止工作，以回避面对痛苦的婚姻真相。"
  },
  {
    "id": 29,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Temporal Regression",
    "zh": "时间退行",
    "defEn": "You focus on earlier times to not think about current conflict.",
    "defZh": "你专注于更早的时光，以回避当下的冲突。",
    "fullDefEn": "You focus on earlier times to not think about current conflict.",
    "caseEn": "A 21-year-old depressed sailor, hospitalized for suicidal ideation, at first",
    "caseZh": "一位40岁的女性在婚姻治疗中，总是不停地回忆她大学时最快乐的一段恋情，而不是讨论现在与丈夫的问题。她通过时间退行回避当下的冲突。"
  },
  {
    "id": 30,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Topographic Regression",
    "zh": "地形学退行",
    "defEn": "You dream to avoid painful reality.",
    "defZh": "你通过做梦来逃避痛苦的现实。",
    "fullDefEn": "You dream to avoid painful reality.",
    "caseEn": "",
    "caseZh": "一位在白天经历了严重车祸的人，当晚做了一个关于在海边平静散步的美梦。通过地形学退行（做梦），他暂时逃避了白天的创伤性现实。"
  },
  {
    "id": 31,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Suppression",
    "zh": "压制",
    "defEn": "You purposely try to forget.",
    "defZh": "你故意试图忘记。",
    "fullDefEn": "You purposely try to forget.",
    "caseEn": "",
    "caseZh": "你在开会前十分钟想'我现在不想去想那个烦人的邮件'，然后真的暂时忘记了它。这是有意识的压制——你主动选择暂时不想。"
  },
  {
    "id": 32,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with a Fantasy",
    "zh": "与幻想认同",
    "defEn": "You act like your favorite hero or heroine.",
    "defZh": "你表现得像你最喜欢的英雄一样。",
    "fullDefEn": "You act like your favorite hero or heroine.",
    "caseEn": "I had just explained to an attractive, 37-year-old woman in treatment that",
    "caseZh": "一个内向的男孩在社交场合模仿他最喜欢的超级英雄的自信姿态和说话方式。通过与幻想认同，他暂时缓解了社交焦虑。"
  },
  {
    "id": 33,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with Parents’ Unconscious or Conscious Wishes/Fantasies",
    "zh": "与父母潜意识或意识中的愿望/幻想认同",
    "defEn": "You do as your parents forbid, act out their corrupt wishes, and get punished.",
    "defZh": "你做父母禁止的事情，把他们堕落的愿望付诸行动，然后受到惩罚。",
    "fullDefEn": "You do as your parents forbid, act out their corrupt wishes, and get punished.",
    "caseEn": "Wishes/Fantasies (Johnson & Szurek, 1952)",
    "caseZh": "一位父亲经常严厉禁止儿子打架，但儿子发现父亲年轻时曾是街头混混。儿子开始频繁打架，无意识中替父亲实现了被禁止的愿望，然后接受惩罚。"
  },
  {
    "id": 34,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with the Ideal Image or Object",
    "zh": "与理想形象或客体认同",
    "defEn": "You think and act like someone you think is great.",
    "defZh": "你像某个你认为伟大的人一样思考和行动。",
    "fullDefEn": "You think and act like someone you think is great.",
    "caseEn": "",
    "caseZh": "一位年轻医生模仿他的导师——一位知名教授——的说话方式、穿着风格甚至诊断思路。通过与理想形象认同，他缓解了对自身能力不足的焦虑。"
  },
  {
    "id": 35,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with the Aggressor",
    "zh": "与攻击者认同",
    "defEn": "You act abusive to a person because someone has acted abusive to you. This protects you from feeling angry.",
    "defZh": "你以虐待的方式对待一个人，因为曾经有人虐待过你。这保护你免于感到愤怒。",
    "fullDefEn": "You act abusive to a person because someone has acted abusive to you. This protects you from feeling angry.",
    "caseEn": "Tip 1. Look for this defense after you’ve been on vacation or otherwise been",
    "caseZh": "一位曾被父亲体罚的女性，在教育自己的孩子时也使用体罚，甚至说出父亲曾对她说过的同样的话。通过与攻击者认同，她保护自己免于回忆起作为受害者的无力感和愤怒。"
  },
  {
    "id": 36,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with the Victim",
    "zh": "与受害者认同",
    "defEn": "You act like someone else by either allowing or seeking victimization. You do this as a rescue wish or to fight off your own anger or guilt.",
    "defZh": "你通过允许或寻求受害来表现得像另一个人，作为一种救赎愿望或为了摆脱愤怒和内疚。",
    "fullDefEn": "You act like someone else by either allowing or seeking victimization. You do this as a rescue wish or to fight off your own anger or guilt.",
    "caseEn": "Mr. S, a 35-year-old assistant pastor, was constantly allowing himself to be",
    "caseZh": "一位童年被忽视的女性，成年后反复选择有虐待倾向的伴侣。通过与受害者认同，她试图通过重新经历受害来掌控它——一种救赎的愿望。"
  },
  {
    "id": 37,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with the Lost Object",
    "zh": "与丧失的客体认同",
    "defEn": "You act like a lost loved one. If you keep souvenirs and never grieve, you’ve got “established pathological mourning” (Volkan, 1987a).",
    "defZh": "你表现得像一个失去的所爱之人。如果保存纪念品且从未哀伤，就是“既定的病态哀悼”。",
    "fullDefEn": "You act like a lost loved one. If you keep souvenirs and never grieve, you’ve got “established pathological mourning” (Volkan, 1987a).",
    "caseEn": "",
    "caseZh": "一位女性在母亲去世三年后仍然每天给母亲的照片摆好餐具。她从未真正哀伤，而是通过表现得像母亲还活着一样（与丧失的客体认同）来回避丧失的痛苦。"
  },
  {
    "id": 38,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Identification with the Introject",
    "zh": "与内摄物认同",
    "defEn": "You make an introject part of your superego.",
    "defZh": "你使一个内摄物成为你超我的一部分。",
    "fullDefEn": "You make an introject part of your superego.",
    "caseEn": "A 30-year-old woman suffering with marital problems and depression",
    "caseZh": "一位男性即使在没有人监督的情况下也不会超速，因为'妈妈说过超速会出人命'。他已将母亲的告诫内摄为超我的一部分。"
  },
  {
    "id": 39,
    "phase": "phallic",
    "phaseEn": "First Genital Phase (2-6 years)",
    "phaseZh": "第一性器期 (2-6岁)",
    "en": "Seduction of the Aggressor",
    "zh": "引诱攻击者",
    "defEn": "You seduce someone sexually or sycophantically to relieve fear. Latency Phase (6 to 11 years)",
    "defZh": "你以性或逢迎的方式诱惑某人，以缓解恐惧。",
    "fullDefEn": "You seduce someone sexually or sycophantically to relieve fear. Latency Phase (6 to 11 years)",
    "caseEn": "Mr. JE, a 30-year-old plumber’s assistant, was upset with his current",
    "caseZh": "一位女性在面对愤怒的男性上司时，用挑逗的语气和肢体语言来缓解自己的恐惧。她通过性诱惑来'驯服'潜在的威胁——引诱攻击者。"
  },
  {
    "id": 40,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Sublimation",
    "zh": "升华",
    "defEn": "You engage in an activity that symbolically represents a fantasy.",
    "defZh": "你从事一个象征性地代表着某种幻想的活动。",
    "fullDefEn": "You engage in an activity that symbolically represents a fantasy.",
    "caseEn": "Parents and teachers strive to interest grade-school children in activities-art,",
    "caseZh": "一个有强烈攻击冲动的青少年成为了一名出色的拳击手。通过升华，他的攻击冲动被导向了社会接受的活动，象征性地代表了搏斗的幻想。"
  },
  {
    "id": 41,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Provocation",
    "zh": "挑衅",
    "defEn": "You get other people to have sex with or punish you, or both.",
    "defZh": "你使他人与你发生性关系或惩罚你，或两者兼有。",
    "fullDefEn": "You get other people to have sex with or punish you, or both.",
    "caseEn": "Ms. LM, 37, brought a lawsuit for mental anguish against a man who had",
    "caseZh": "一位女性在治疗中不断说一些挑衅治疗师的话，似乎想激治疗师发火或批评她。她无意识中寻求被惩罚来缓解内疚感。"
  },
  {
    "id": 42,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Rationalization",
    "zh": "合理化",
    "defEn": "You make excuses to relieve tension, usually after denying some reality.",
    "defZh": "你制造借口来缓解紧张，通常是在否认某些现实之后。",
    "fullDefEn": "You make excuses to relieve tension, usually after denying some reality.",
    "caseEn": "",
    "caseZh": "一个考试不及格的学生说'反正这门课也没什么用，老师教得也不好'。他用合理化来缓解不及格带来的羞耻感。"
  },
  {
    "id": 43,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Rumination",
    "zh": "穷思竭虑",
    "defEn": "You “overanalyze” and “spin your wheels” trying to solve problems.",
    "defZh": "你“过度分析”和“反复纠结”试图解决问题。",
    "fullDefEn": "You “overanalyze” and “spin your wheels” trying to solve problems.",
    "caseEn": "A 35-year-old divorced woman spent weeks in therapy trying to “figure",
    "caseZh": "一位来访者反复思考'他为什么说那句话？他说那句话到底是什么意思？我是不是做错了什么？但也许他只是心情不好……'她用穷思竭虑来避免直接面对焦虑。"
  },
  {
    "id": 44,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Counterphobic Behavior",
    "zh": "反恐惧行为",
    "defEn": "You do exactly what scares you.",
    "defZh": "你越是害怕什么，就越去做什么。",
    "fullDefEn": "You do exactly what scares you.",
    "caseEn": "An analyst colleague felt, after careful evaluation, that her narcissistic male",
    "caseZh": "一个害怕高的人却去学攀岩；一个怕当众讲话的人报名参加演讲比赛。通过反恐惧行为，他们主动面对恐惧来证明'我不怕'。"
  },
  {
    "id": 45,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Intellectualization",
    "zh": "理智化",
    "defEn": "You get cranked up about a peculiar theory of behavior.",
    "defZh": "你沉迷于某个特定的行为理论，以此回避情感。",
    "fullDefEn": "You get cranked up about a peculiar theory of behavior.",
    "caseEn": "A 42-year-old male college professor confessed during evaluation that he",
    "caseZh": "一个在派对上感到社交焦虑的人，开始滔滔不绝地讲述他最近读的一本冷门哲学书。他用理智化来避免感受社交焦虑。"
  },
  {
    "id": 46,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Socialization and Distancing",
    "zh": "社会化与疏远",
    "defEn": "You use your social ability to distract yourself from painful thoughts.",
    "defZh": "你用社交能力来分散注意力，使自己远离痛苦的想法。",
    "fullDefEn": "You use your social ability to distract yourself from painful thoughts.",
    "caseEn": "LATENCY, ADOLESCENT, AND ASSORTED OTHER DEFENSES 51",
    "caseZh": "一位刚经历失恋的人疯狂地参加各种社交活动，每天排满饭局和聚会。他用社会化与疏远来避免独处时面对失恋的痛苦。"
  },
  {
    "id": 47,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Instinctualization of an Ego Function",
    "zh": "自我功能的本能化",
    "defEn": "You attach symbolic meaning to an ego function (e.g., “Washing dishes is women’s work” irrationally equates a certain type of work with gender).",
    "defZh": "你给一种自我功能赋予象征性的含义（如“洗碗是女人的工作”不合理地把工作类型等同于性别）。",
    "fullDefEn": "You attach symbolic meaning to an ego function (e.g., “Washing dishes is women’s work” irrationally equates a certain type of work with gender).",
    "caseEn": "High school class clowns sexualize speech by finding sexual meanings in",
    "caseZh": "一个人坚持认为'做饭是女人的事'。通过将某种工作功能本能化（赋予性别含义），他回避了学习做饭可能带来的无能感。"
  },
  {
    "id": 48,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Inhibition of an Ego Function",
    "zh": "自我功能的抑制",
    "defEn": "Your instinctualized ego function clashes with guilt, so you shut off the function (e.g., you can’t read because reading is equated with forbidden sexual activity [Anthony, 1961]).",
    "defZh": "你的本能化自我功能与内疚冲突，于是关闭了该功能（如无法阅读，因为阅读被等同于被禁止的性活动）。",
    "fullDefEn": "Your instinctualized ego function clashes with guilt, so you shut off the function (e.g., you can’t read because reading is equated with forbidden sexual activity [Anthony, 1961]).",
    "caseEn": "Ms. N, a 32-year-old, divorced, educated woman, requested insightdirected",
    "caseZh": "一个青少年突然'无法'阅读了，因为阅读在无意识中被等同于被禁止的性活动。他关闭了这个自我功能来避免内疚。"
  },
  {
    "id": 49,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Idealization",
    "zh": "理想化",
    "defEn": "You overvalue someone because of: a. narcissism (Freud, 1914a): to relieve shame over your inadequacy b. narcissism (Kohut, 1971): you fuse the person with your overestimated self-image (“selfobject”)...",
    "defZh": "你过于看重某人，原因可能是：a) 自恋：减轻因自身缺陷引起的羞愧；b) 自恋（科胡特）：将对方与夸大的自体影像融合；c) 爱：为不体验到失望；d) 移情：对方像你幼年时美好的父母。",
    "fullDefEn": "You overvalue someone because of: a. narcissism (Freud, 1914a): to relieve shame over your inadequacy b. narcissism (Kohut, 1971): you fuse the person with your overestimated self-image (“selfobject”) c. love: to not experience disappointments d. transference (Freud, 1914b): they’re like a wonderful parent, when you were little.",
    "caseEn": "(Kohut, 1971): people confuse another person with an overestimation of",
    "caseZh": "一位来访者在治疗初期把治疗师描述为'完美的''无所不知的''能解决一切问题的人'。通过理想化，他减轻了自身缺陷带来的羞耻，也避免了对治疗师可能的失望。"
  },
  {
    "id": 50,
    "phase": "latency",
    "phaseEn": "Latency Phase (6-11 years)",
    "phaseZh": "潜伏期 (6-11岁)",
    "en": "Devaluation",
    "zh": "贬低",
    "defEn": "You look down on someone to preserve your own self- esteem. Adolescence and Later-Second Genital Phase (13 to 20 years plus)",
    "defZh": "你看不起某人以维护自己的自尊。",
    "fullDefEn": "You look down on someone to preserve your own self- esteem. Adolescence and Later-Second Genital Phase (13 to 20 years plus)",
    "caseEn": "Although fairly overt in narcissistic people, devaluation can occur more subtly.",
    "caseZh": "一位能力平平的经理不断贬低他手下最能干的下属，说对方'也就那样''没什么了不起'。通过贬低，他维护了自己脆弱的自尊。"
  },
  {
    "id": 51,
    "phase": "adolescent",
    "phaseEn": "Adolescence & Later (13-20+ years)",
    "phaseZh": "青春期及以后 (13-20岁+)",
    "en": "Humor",
    "zh": "幽默",
    "defEn": "You use kidding around to avoid painful feelings. If you get extremely wound up, you’re hypomanic (Lewin, 1950; Almansi, 1961).",
    "defZh": "你用开玩笑来避免痛苦的感受。如果过度兴奋，可能是轻躁狂。",
    "fullDefEn": "You use kidding around to avoid painful feelings. If you get extremely wound up, you’re hypomanic (Lewin, 1950; Almansi, 1961).",
    "caseEn": "Mr. OD, a 33-year-old, dyed-in-the-wool New Yorker transplanted to the",
    "caseZh": "一个人在讲述自己婚姻破裂的痛苦时，不断插入自嘲的玩笑。他用幽默来避免完全体验悲伤和愤怒。"
  },
  {
    "id": 52,
    "phase": "adolescent",
    "phaseEn": "Adolescence & Later (13-20+ years)",
    "phaseZh": "青春期及以后 (13-20岁+)",
    "en": "Concretization",
    "zh": "具体化",
    "defEn": "You stop using abstract thinking (which you have); you blame a “chemical imbalance” or look for a virus to avoid thinking relationships make you upset.",
    "defZh": "你停止使用抽象思维（你本具备的）；你责怪“化学物质失衡”或寻找病毒，以避免思考人际关系令你烦恼。",
    "fullDefEn": "You stop using abstract thinking (which you have); you blame a “chemical imbalance” or look for a virus to avoid thinking relationships make you upset.",
    "caseEn": "Ms. PW responded that she was embarrassed that she had once been",
    "caseZh": "一个与妻子关系紧张的男人坚持认为自己的问题是'血清素失衡'，只需要吃药就行，拒绝讨论婚姻问题。他用具体化（化学物质失衡这种具象解释）来回避人际关系带来的痛苦。"
  },
  {
    "id": 53,
    "phase": "adolescent",
    "phaseEn": "Adolescence & Later (13-20+ years)",
    "phaseZh": "青春期及以后 (13-20岁+)",
    "en": "Disidentification",
    "zh": "去认同化",
    "defEn": "You endeavor not to be like one of your parents.",
    "defZh": "你努力让自己不像父母之一。",
    "fullDefEn": "You endeavor not to be like one of your parents.",
    "caseEn": "LZ, a 21-year-old woman, reluctantly complained that she was having",
    "caseZh": "一个男孩的父亲是酒鬼，他发誓'我绝对不会成为我父亲那样的人'，于是滴酒不沾、极度自律。通过与父亲去认同化，他回避了对与父亲相似的恐惧。"
  },
  {
    "id": 54,
    "phase": "adolescent",
    "phaseEn": "Adolescence & Later (13-20+ years)",
    "phaseZh": "青春期及以后 (13-20岁+)",
    "en": "Group formation",
    "zh": "团体形成",
    "defEn": "You surround yourself to guard against sexual impulses.",
    "defZh": "你把自己包围在团体中以防御性冲动。",
    "fullDefEn": "You surround yourself to guard against sexual impulses.",
    "caseEn": "A young married couple consulted me because of fights. The wife objected",
    "caseZh": "一个青少年加入了一个要求成员始终保持集体行动的宗教团体。通过团体形成，他用群体的力量来防御自己对性冲动的恐惧。"
  },
  {
    "id": 55,
    "phase": "adolescent",
    "phaseEn": "Adolescence & Later (13-20+ years)",
    "phaseZh": "青春期及以后 (13-20岁+)",
    "en": "Asceticism",
    "zh": "禁欲主义",
    "defEn": "You avoid contact with humans.",
    "defZh": "你避免与人接触。",
    "fullDefEn": "You avoid contact with humans.",
    "caseEn": "A 55-year-old retired Navy Captain had never been married. His sex life",
    "caseZh": "一个人在感情受伤后，搬到深山里独居，避免与任何人接触。通过禁欲主义，他回避了再次被伤害的可能。"
  },
  {
    "id": 56,
    "phase": "adolescent",
    "phaseEn": "Adolescence & Later (13-20+ years)",
    "phaseZh": "青春期及以后 (13-20岁+)",
    "en": "Ipsisexual Object Choice",
    "zh": "同性客体选择",
    "defEn": "Your same-sex “buddy” allays fear of heterosexual stimulation. Assorted",
    "defZh": "你的同性“伙伴”缓解了对异性刺激的恐惧。",
    "fullDefEn": "Your same-sex “buddy” allays fear of heterosexual stimulation. Assorted",
    "caseEn": "",
    "caseZh": "一个对异性感到极度焦虑的男性，选择只与同性朋友密切交往，称对方为'最好的兄弟'。通过同性客体选择，他避免了与异性亲密接触带来的恐惧。"
  },
  {
    "id": 57,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "One affect versus Another",
    "zh": "一种情感对另一种情感",
    "defEn": "You focus on one emotion to avoid another.",
    "defZh": "你专注于一种情感以回避另一种。",
    "fullDefEn": "You focus on one emotion to avoid another.",
    "caseEn": "Parents who overreact to their teenager’s staying out late by getting overly",
    "caseZh": "一个对父母感到愤怒但无法表达的人，转而过度强调自己对父母的爱和感激。他专注于爱这种情感，以回避愤怒。"
  },
  {
    "id": 58,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Hyperabstraction",
    "zh": "过度抽象化",
    "defEn": "You abuse theories. If you also deny and reconstruct reality, you’re probably psychotic.",
    "defZh": "你滥用理论。如果你还否认并重构现实，那么多半是精神病性的。",
    "fullDefEn": "You abuse theories. If you also deny and reconstruct reality, you’re probably psychotic.",
    "caseEn": "Although in schizophrenia we usually see deficiencies in abstraction ability,",
    "caseZh": "一个无法处理婚姻矛盾的人，开始用艰涩的哲学理论来解释自己的处境，说'存在先于本质，所以我的婚姻注定如此'。他滥用理论（过度抽象化）来否认和重构现实。"
  },
  {
    "id": 59,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Reticence",
    "zh": "缄默",
    "defEn": "You stop speaking to avoid being found out.",
    "defZh": "你停止讲话以避免被看穿。",
    "fullDefEn": "You stop speaking to avoid being found out.",
    "caseEn": "The “Silent Cal,” chronically, automatically quiet and unresponsive as an",
    "caseZh": "一位来访者在治疗中一旦接近核心创伤话题就陷入长时间的沉默。她用缄默来避免被看穿。"
  },
  {
    "id": 60,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Garrulousness",
    "zh": "饶舌",
    "defEn": "You’re talking too much, but aren’t circumstantial or tangential.",
    "defZh": "你说得太多，但并不详细或切题。",
    "fullDefEn": "You’re talking too much, but aren’t circumstantial or tangential.",
    "caseEn": "In people with so-called histrionic traits, their talkativeness protects them from",
    "caseZh": "一位社交场合中感到紧张的人不停地说一些无关紧要的话，填满每一个沉默的间隙。他用饶舌来回避焦虑和孤独感。"
  },
  {
    "id": 61,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Avoidance",
    "zh": "回避",
    "defEn": "You stay away from situations due to the conflicts they generate.",
    "defZh": "你远离某些情境，因为它们产生冲突。",
    "fullDefEn": "You stay away from situations due to the conflicts they generate.",
    "caseEn": "Avoidance is usually a secondary defensive operation, after defenses such as",
    "caseZh": "一个人因为害怕面对前女友，绕远路避免经过她工作的街区。他用回避来远离产生冲突的情境。"
  },
  {
    "id": 62,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Passivity",
    "zh": "被动",
    "defEn": "You automatically adopt a compliant or submissive attitude in the face of aggression.",
    "defZh": "你在面对攻击时自动采取顺从或唯命是从的态度。",
    "fullDefEn": "You automatically adopt a compliant or submissive attitude in the face of aggression.",
    "caseEn": "Pathological, defensive passivity usually wards off unconscious guilt over",
    "caseZh": "一位员工在被老板不公平对待时，不仅不反驳，反而更加顺从和讨好。他用被动（自动顺从的态度）来回避直接面对攻击带来的恐惧。"
  },
  {
    "id": 63,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Grandiosity/Omnipotence",
    "zh": "夸大/全能感",
    "defEn": "You are God’s gift to earth, have special powers.",
    "defZh": "你认为自己是上帝送给地球的礼物，拥有特殊力量。",
    "fullDefEn": "You are God’s gift to earth, have special powers.",
    "caseEn": "Mr. Q, a 23-year-old male graduate student with a study inhibition, had",
    "caseZh": "一位年轻医生宣称自己发明了一种全新的治疗方法，比其他所有人都先进。他用夸大/全能感来缓解对自身经验不足的焦虑。"
  },
  {
    "id": 64,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Passive to Active",
    "zh": "被动转主动",
    "defEn": "“You can’t fire me; I quit!” You control your own victimization.",
    "defZh": "“你不能开除我；我辞职！”你控制自己的受害。",
    "fullDefEn": "“You can’t fire me; I quit!” You control your own victimization.",
    "caseEn": "Without awareness of their defensive motivations, abused children will often",
    "caseZh": "一个知道公司即将裁员的人，主动递交了辞职信，说'你不能开除我，我辞职！'。通过被动转主动，他控制了自己的受害。"
  },
  {
    "id": 65,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Somatization",
    "zh": "躯体化",
    "defEn": "You focus on your body to avoid conflicts with oral, sexual, or hostile impulses.",
    "defZh": "你专注于自己的身体以避免与口欲、性或敌意冲动的冲突。",
    "fullDefEn": "You focus on your body to avoid conflicts with oral, sexual, or hostile impulses.",
    "caseEn": "A 55-year-old divorced businesswoman had developed pain in her",
    "caseZh": "一位在婚姻中极度不快乐的女性，不断就医检查身体的各种小毛病，但拒绝讨论她的婚姻问题。她用躯体化（专注身体）来回避关系冲突。"
  },
  {
    "id": 66,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Normalization",
    "zh": "正常化",
    "defEn": "You convince yourself you are normal despite obvious psychopathology.",
    "defZh": "你使自己相信你是正常的，尽管存在明显的精神病理。",
    "fullDefEn": "You convince yourself you are normal despite obvious psychopathology.",
    "caseEn": "",
    "caseZh": "一个有严重酗酒问题的人说'大家都喝酒啊，我没什么不正常的'。她用正常化来使自己相信自己是正常的，尽管存在明显的精神病理。"
  },
  {
    "id": 67,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Dramatization",
    "zh": "戏剧化",
    "defEn": "You inject emotion into your speech to relieve conflict about being noticed.",
    "defZh": "你在言谈中注入情绪以缓解关于不被注意的冲突。",
    "fullDefEn": "You inject emotion into your speech to relieve conflict about being noticed.",
    "caseEn": "",
    "caseZh": "一位来访者在讲述一个平凡的故事时，辅以夸张的手势和戏剧性的语调。她用戏剧化来缓解关于不被注意的焦虑。"
  },
  {
    "id": 68,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Impulsivity",
    "zh": "冲动化",
    "defEn": "You use sex, eating, or hostility to relieve tension or an unpleasant affect.",
    "defZh": "你用性、进食或敌意来缓解紧张或不愉快的情感。",
    "fullDefEn": "You use sex, eating, or hostility to relieve tension or an unpleasant affect.",
    "caseEn": "As a defense, a person acts on an urge in order to relieve tension or an",
    "caseZh": "一个在考试前焦虑不安的学生，一口气吃掉了一整盒冰淇淋和一包薯片。他用冲动化（进食）来缓解紧张。"
  },
  {
    "id": 69,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Substance Abuse",
    "zh": "物质滥用",
    "defEn": "You use a concoction to quell unpleasurable affects.",
    "defZh": "你用物质来镇压不愉快的情感。",
    "fullDefEn": "You use a concoction to quell unpleasurable affects.",
    "caseEn": "Most of the media focus on drug and alcohol abusers concerns ego weakness",
    "caseZh": "一个社交焦虑的人在参加聚会前必须喝几杯酒。他用物质滥用来镇压不愉快的情感。"
  },
  {
    "id": 70,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Clinging",
    "zh": "黏附",
    "defEn": "Clutching onto a person who rejects you.",
    "defZh": "紧紧抓住一个拒绝你的人。",
    "fullDefEn": "Clutching onto a person who rejects you.",
    "caseEn": "",
    "caseZh": "一位女性在男友明显对她冷淡并提出分手后，反而更加紧抓不放，每天打十几个电话。她用黏附来回避被抛弃的恐惧。"
  },
  {
    "id": 71,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Whining",
    "zh": "抱怨",
    "defEn": "Complaining, you don’t see the infantile quality of your wish to be taken care of.",
    "defZh": "不停地抱怨，你没有看到自己想被照顾的幼稚愿望。",
    "fullDefEn": "Complaining, you don’t see the infantile quality of your wish to be taken care of.",
    "caseEn": "",
    "caseZh": "一位员工不停向同事抱怨工作有多糟糕、老板有多不公，但从不采取任何行动改变。他用抱怨来表达想被照顾的幼稚愿望。"
  },
  {
    "id": 72,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Pseudoindependence",
    "zh": "假性独立",
    "defEn": "You become the Lone Ranger, not allowing anyone to help you.",
    "defZh": "你变成独行侠，不允许任何人帮助你。",
    "fullDefEn": "You become the Lone Ranger, not allowing anyone to help you.",
    "caseEn": "Mr. K, a 61-year-old investment banker, had just had a heart attack. In",
    "caseZh": "一个正在经历严重困难的人拒绝所有朋友的帮助，坚持'我自己能行'。他用假性独立来回避依赖带来的脆弱感。"
  },
  {
    "id": 73,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Pathological altruism",
    "zh": "病理性利他主义",
    "defEn": "Actually projection and identification with the victim: you deny oral urges, project them onto the needy, then vicariously feel nurtured.",
    "defZh": "实际上是投射和与受害者认同：你否认口欲欲望，将其投射到贫困者身上，然后替代性地感到被滋养。",
    "fullDefEn": "Actually projection and identification with the victim: you deny oral urges, project them onto the needy, then vicariously feel nurtured.",
    "caseEn": "",
    "caseZh": "一位极力否认自己有被照顾需求的人，却整天忙着照顾无家可归者，为他们提供食宿。通过病理性利他主义，她把自己的口欲需求投射到贫困者身上，然后替代性地感到被滋养。"
  },
  {
    "id": 74,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Gaslighting",
    "zh": "煤气灯效应",
    "defEn": "You cause people to be mentally disturbed or to believe they are.",
    "defZh": "你导致别人变得精神失常或相信自己精神失常。",
    "fullDefEn": "You cause people to be mentally disturbed or to believe they are.",
    "caseEn": "",
    "caseZh": "一个丈夫在妻子质疑他的不忠时，不断告诉妻子'你太多疑了'、'你是不是该看心理医生了'。他用煤气灯效应使妻子怀疑自己的现实感知。"
  },
  {
    "id": 75,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Minimization",
    "zh": "最小化",
    "defEn": "You are conscious of a painful reality but give that reality little weight.",
    "defZh": "你意识到一个痛苦的现实但有意轻视它的重要性。",
    "fullDefEn": "You are conscious of a painful reality but give that reality little weight.",
    "caseEn": "",
    "caseZh": "一个被诊断出严重疾病的病人说'这没什么大不了的，很多人比我更糟'。他用最小化来减轻面对重大疾病时的恐惧。"
  },
  {
    "id": 76,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Exaggeration",
    "zh": "夸大",
    "defEn": "You make too much of a deal over something.",
    "defZh": "你在某件事上渲染得太过头了。",
    "fullDefEn": "You make too much of a deal over something.",
    "caseEn": "Ms. PQ worried because her only child, a 2-year-old girl, would sometimes",
    "caseZh": "一个人在求职被拒后，说'这是我这辈子最灾难性的失败，我永远也找不到工作了'。他用夸大来给自己对失败的愤怒找到一个看似合理的出口。"
  },
  {
    "id": 77,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Generalization",
    "zh": "泛化",
    "defEn": "To not hate someone, you see him as part of an evil group.",
    "defZh": "为了不去憎恨某个人，你把他看成是某个邪恶群体的一部分。",
    "fullDefEn": "To not hate someone, you see him as part of an evil group.",
    "caseEn": "A married, middle-aged man realizes, through analytic treatment, that his",
    "caseZh": "一个人因为不喜欢某个同事，不说'我不喜欢他'，而是说'他们那个部门的人都一个德行'。他用泛化来避免直接面对对某人的负面情感。"
  },
  {
    "id": 78,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Reconstruction of Reality",
    "zh": "重构现实",
    "defEn": "You reinvent a situation after denying the reality.",
    "defZh": "在否认现实之后，你重塑一个状况。",
    "fullDefEn": "You reinvent a situation after denying the reality.",
    "caseEn": "Neurotic people do this to relieve guilt or anxiety. Kanzer (1953) suggests that",
    "caseZh": "一个被伴侣抛弃的人，重新编织了一套叙事，说'其实是我早就想分手了，是我故意让他离开的'。在否认被抛弃的现实后，她重构了现实以保护自尊。"
  },
  {
    "id": 79,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Transference",
    "zh": "移情",
    "defEn": "You shift memories of past situations and relationships onto a current person. You then use old defenses to forget the past or to master it by living it again symbolically or changing the ending.",
    "defZh": "你将对既往情境和人际关系的记忆转移到当下的人身上。然后用旧的防御来忘记过去，或通过象征性地再次经历或改写结果来征服过去。",
    "fullDefEn": "You shift memories of past situations and relationships onto a current person. You then use old defenses to forget the past or to master it by living it again symbolically or changing the ending.",
    "caseEn": "Dr. G, a 40-year-old surgeon, consulted me because he was always late. This",
    "caseZh": "一位来访者在治疗中开始对治疗师产生强烈的情感——既像对母亲一样渴望关爱，又像对母亲一样感到愤怒。这些对过去关系的记忆被转移到了治疗师身上，这是移情。"
  },
  {
    "id": 80,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Dissociation",
    "zh": "解离",
    "defEn": "(1) You forget a whole aspect of yourself. If you name it Butch, you are probably psychotic (Frosch, 1983; Gardner, 1994). (2) You get someone to define you, then reject his or her ideas (Whitmer, 200...",
    "defZh": "1) 你忘记了关于自己的完整面貌；如果给它取名，多半是精神病性的。2) 你让别人定义你，然后驳回对方的想法。",
    "fullDefEn": "(1) You forget a whole aspect of yourself. If you name it Butch, you are probably psychotic (Frosch, 1983; Gardner, 1994). (2) You get someone to define you, then reject his or her ideas (Whitmer, 2001).",
    "caseEn": "Some therapists and analysts (I.Brenner, 1996, 2001) have reported finding",
    "caseZh": "一位童年遭受虐待的女性有时会'变成'一个完全不同的人格——用另一个名字、另一种声音说话，声称自己从未受过伤害。通过解离，她忘记了完整的自己。"
  },
  {
    "id": 81,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Photophobia",
    "zh": "恐光症",
    "defEn": "You avoid the light to avoid your scoptophilic (voyeuristic) impulses.",
    "defZh": "你回避光线，以回避你的窥视冲动。",
    "fullDefEn": "You avoid the light to avoid your scoptophilic (voyeuristic) impulses.",
    "caseEn": "",
    "caseZh": "一个广场恐怖症患者避免出门，部分原因是回避光线和开放空间——光线会让人感觉被'看见'，这与被观看的焦虑（窥视冲动）有关。"
  },
  {
    "id": 82,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Apathy",
    "zh": "冷漠",
    "defEn": "You have no particular interest in engaging in an activity.",
    "defZh": "你对参与任何活动都没有特别的兴趣。",
    "fullDefEn": "You have no particular interest in engaging in an activity.",
    "caseEn": "Apathetic people are not necessarily lazy or negative. Their apparent lack of",
    "caseZh": "一个刚被解雇的人说'反正我也不在乎那份工作'，对找工作完全提不起兴趣。他用冷漠来回避失业带来的羞耻和焦虑。"
  },
  {
    "id": 83,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Intimidation of Others — Bullying",
    "zh": "恐吓他人/欺凌",
    "defEn": "You put others on guard to relieve your own anxiety.",
    "defZh": "你使他人处于戒备状态以缓解自己的焦虑。",
    "fullDefEn": "You put others on guard to relieve your own anxiety.",
    "caseEn": "",
    "caseZh": "一个在学校里不安全的男孩通过欺负比他更小的孩子来建立自己的地位。通过恐吓他人，他缓解了自己的焦虑。"
  },
  {
    "id": 84,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Compensation for Deficiencies",
    "zh": "弥补不足",
    "defEn": "You ostracize those who are more integrated than you are.",
    "defZh": "你排斥那些比你更加整合的人。",
    "fullDefEn": "You ostracize those who are more integrated than you are.",
    "caseEn": "A 31-year-old single man was still working on his bachelor’s degree from",
    "caseZh": "一个在工作中表现平平的员工，排斥和疏远那些表现优秀的同事，说他们'拍马屁''假正经'。他用弥补不足（排斥更优秀的人）来维护自尊。"
  },
  {
    "id": 85,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Psychogenic Tic",
    "zh": "心因性抽动",
    "defEn": "Twitching to relieve tension/anger.",
    "defZh": "抽动以缓解紧张/愤怒。",
    "fullDefEn": "Twitching to relieve tension/anger.",
    "caseEn": "Mahler (1944) differentiates psychogenic tic from neurologically based",
    "caseZh": "一个人在压抑愤怒时出现不自主的眼部抽动。这种心因性抽动在无意识中释放了紧张和愤怒。"
  },
  {
    "id": 86,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Introspection",
    "zh": "内省",
    "defEn": "You preoccupy yourself with inner musings to relieve tension or to sidestep external realities.",
    "defZh": "你全神贯注于内在沉思以缓解紧张或回避外在现实。",
    "fullDefEn": "You preoccupy yourself with inner musings to relieve tension or to sidestep external realities.",
    "caseEn": "",
    "caseZh": "一个人花大量时间独处于内心世界，反复思考人生的意义。虽然看起来像是在'自我探索'，但其实是用内省来回避外在现实中的人际关系问题。"
  },
  {
    "id": 87,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Qualified Agreement",
    "zh": "有保留的同意",
    "defEn": "You partly agree as a way of avoiding rebelliousness.",
    "defZh": "你表达部分同意，作为回避叛逆情绪的方式。",
    "fullDefEn": "You partly agree as a way of avoiding rebelliousness.",
    "caseEn": "I have in mind those individuals who react not with doubt or disputation,",
    "caseZh": "一个青少年在被父母训斥时，说'好吧，你们说的有些道理'，但实际上内心完全不认同。他用有保留的同意来避免直接叛逆带来的冲突。"
  },
  {
    "id": 88,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Instinctualization of an Ego Weakness",
    "zh": "自我弱点的本能化",
    "defEn": "You give a gender connotation to your weakness in affect-tolerance or impulse control (masculine or feminine).",
    "defZh": "你给自己在情感容忍度或冲动控制方面的弱点赋予性别内涵（雄性或雌性）。",
    "fullDefEn": "You give a gender connotation to your weakness in affect-tolerance or impulse control (masculine or feminine).",
    "caseEn": "In heterosexual men who are so troubled by homosexual fantasies (Coates &",
    "caseZh": "一个对自己情绪控制能力差感到羞耻的男性，把这归因为'我性格就是比较man，直来直去'。他将自我弱点本能化（赋予男性气质），回避面对情绪管理的问题。"
  },
  {
    "id": 89,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Inauthenticity",
    "zh": "不真实",
    "defEn": "You fake it, perhaps habitually.",
    "defZh": "你伪装事实，可能是习惯性的。",
    "fullDefEn": "You fake it, perhaps habitually.",
    "caseEn": "Although it is not uncommon for adolescents to “try on” various roles, to",
    "caseZh": "一个人在社交场合中总是戴着一副'面具'，用不真实的自我呈现来隐藏真实的感受和想法。"
  },
  {
    "id": 90,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Hyper-Rationality",
    "zh": "超合理性",
    "defEn": "You use secondary process to avoid affects.",
    "defZh": "你使用次级过程来回避情感。",
    "fullDefEn": "You use secondary process to avoid affects.",
    "caseEn": "",
    "caseZh": "一个面对婚姻危机的人，用极其冷静、逻辑清晰的方式分析婚姻问题的'数据'和'概率'，但始终不触及自己的悲伤和恐惧。他使用超合理性来回避情感。"
  },
  {
    "id": 91,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Vagueness",
    "zh": "含糊",
    "defEn": "You hide details.",
    "defZh": "你隐藏细节。",
    "fullDefEn": "You hide details.",
    "caseEn": "A middle-aged woman complained in session that she had “a terrible",
    "caseZh": "一个被问到'你周末做了什么'的人回答说'没做什么特别的，就到处转转'，其实他周末去见了一个重要的旧友。他用含糊来隐藏细节。"
  },
  {
    "id": 92,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Hyper-Aestheticism",
    "zh": "超唯美主义",
    "defEn": "You get into beauty and truth, avoiding reality or affects.",
    "defZh": "你沉迷于美和真理中，回避现实或情感。",
    "fullDefEn": "You get into beauty and truth, avoiding reality or affects.",
    "caseEn": "",
    "caseZh": "一个人沉浸在艺术品和古典音乐中，用对美和真理的追求来回避处理现实生活中的关系和问题。"
  },
  {
    "id": 93,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Glibness",
    "zh": "油嘴滑舌",
    "defEn": "You speak readily but don’t mean much of it.",
    "defZh": "你毫不犹豫地说着话，但并没有想要表达很多。",
    "fullDefEn": "You speak readily but don’t mean much of it.",
    "caseEn": "A single, 35-year-old woman in treatment reported a dream in which a man",
    "caseZh": "一个人在重要会议上轻松地说着漂亮话，但仔细一听其实什么实质内容都没说。他用油嘴滑舌来回避真正的交流。"
  },
  {
    "id": 94,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Physical Violence",
    "zh": "身体暴力",
    "defEn": "You “nullify the object,” halting your hatred.",
    "defZh": "你“作废客体”，终止你的仇恨。",
    "fullDefEn": "You “nullify the object,” halting your hatred.",
    "caseEn": "Physical violence has a long and controversial history-pacifists versus",
    "caseZh": "一位童年遭受暴力的男性，成年后在愤怒时也会对伴侣使用暴力。通过身体暴力，他'作废'了激发他仇恨的客体，以此终止无法忍受的仇恨感。"
  },
  {
    "id": 95,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Identification with the Injured Object",
    "zh": "与受伤客体认同",
    "defEn": "You model yourself after wounded birds you’ve known (and sometimes, loved).",
    "defZh": "你仿效自己认识的（有时是所爱的）受伤小鸟。",
    "fullDefEn": "You model yourself after wounded birds you’ve known (and sometimes, loved).",
    "caseEn": "A 40-year-old man was not finishing his work. He then would confess this",
    "caseZh": "一位治疗师发现自己特别容易被'受伤的'来访者吸引，总是想要'拯救'他们。他可能在仿效童年时认识的一个受伤的人（也许是抑郁的母亲），这是与受伤客体认同。"
  },
  {
    "id": 96,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Formal Regression",
    "zh": "形式退行",
    "defEn": "You stop using logical, time-oriented thought.",
    "defZh": "你停止使用逻辑的、时间导向的思维。",
    "fullDefEn": "You stop using logical, time-oriented thought.",
    "caseEn": "",
    "caseZh": "一个人在讨论复杂的情感问题时，突然开始用极其简单、非逻辑的方式说话，像是回到了儿童的思维方式。他通过形式退行回避了逻辑思维可能带来的痛苦洞察。"
  },
  {
    "id": 97,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Hypervigilance",
    "zh": "过度警觉",
    "defEn": "You keep an eye out all the time, even when it’s entirely unnecessary.",
    "defZh": "你总是随时留意着，即使完全没有必要。",
    "fullDefEn": "You keep an eye out all the time, even when it’s entirely unnecessary.",
    "caseEn": "",
    "caseZh": "一位创伤后应激障碍患者即使在安全的环境中也无法放松，不停地扫视周围、检查出口。他用过度警觉来防御再次受创的可能。"
  },
  {
    "id": 98,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Temporal Displacement to the Future",
    "zh": "时间置换到未来",
    "defEn": "You imagine “if only…” or “someday…”",
    "defZh": "你想象着“只要……”或“有朝一日……”",
    "fullDefEn": "You imagine “if only…” or “someday…”",
    "caseEn": "",
    "caseZh": "一个在困境中的人不断说'总有一天一切都会好起来的'、'只要等到明年就好了'。他用时间置换到未来来回避面对当下的无力感。"
  },
  {
    "id": 99,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Fatigue",
    "zh": "疲劳",
    "defEn": "You feel tired, but you’re not physically ill.",
    "defZh": "你感到疲惫，但没有躯体疾病。",
    "fullDefEn": "You feel tired, but you’re not physically ill.",
    "caseEn": "Fatigue is an extremely common complaint heard in general medical practices.",
    "caseZh": "一个面对繁重工作任务的人突然感到极度疲惫，但体检一切正常。这种疲劳是一种心理防御，避免面对工作带来的焦虑或挫败感。"
  },
  {
    "id": 100,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Frankness",
    "zh": "直率",
    "defEn": "You’re honest and blunt, but this covers up your actual thoughts and feelings.",
    "defZh": "你诚实而坦率，但这点掩饰了你实际的想法和情感。",
    "fullDefEn": "You’re honest and blunt, but this covers up your actual thoughts and feelings.",
    "caseEn": "LATENCY, ADOLESCENT, AND ASSORTED OTHER DEFENSES 91",
    "caseZh": "一个人对朋友直言不讳地说'你穿这件衣服看起来很胖'，然后补充说'我只是实话实说'。他用直率作为防御，掩盖了话中隐含的攻击性。"
  },
  {
    "id": 101,
    "phase": "assorted",
    "phaseEn": "Assorted",
    "phaseZh": "杂类",
    "en": "Turning Self-Criticism onto the Object",
    "zh": "将自我批判转向客体",
    "defEn": "Criticism onto the Object—You criticize somebody else instead of berating yourself.",
    "defZh": "你批评别人而不是责备自己。",
    "fullDefEn": "Criticism onto the Object—You criticize somebody else instead of berating yourself.",
    "caseEn": "Mr. UV, a 33-year-old man hospitalized for suicidal ideation, complained",
    "caseZh": "UV先生因自杀意念住院，他不断批评妻子太胖、吃太多。治疗师指出他自己也有体重问题，他批评妻子的实际上是他不想在自己身上看到的东西。他将自我批判转向了客体。"
  }
];
